### PR TITLE
fix(core): Correctly resize drawing buffer on resize

### LINKED ISSUE #9856: [Bug] GoogleMapsOverlay not working properly with Vector mapId in fullscreen mode / on resize
### Description

I'm trying to add a `BitmapLayer` and `PolygonLayer` on top of Google Maps using a `GoogleMapsOverlay`. When the used `mapId` is configured to use a rasterised map everything works properly; both an embedded map and fullscreen map. However, as soon as I configure the `mapId` to use vector maps and I go full screen or resize the embedded map the bitmap is not drawn at the correct position anymore (without any changes in my code).

### Flavors

- [ ] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [x] GoogleMapsOverlay
- [ ] CARTO
- [ ] ArcGIS

### Expected Behavior

Both rasterised and vector layers should display at the same positions.

### Steps to Reproduce

- Edit `app.js` of the `get-started/pure-js/google-maps` example.
- Add a `BitmapLayer` with an image and coordinates at a position of your choice.
- Use a `mapId` that is configured to use vector layers.
- Open the example and switch to fullscreen.

NOTE: When I followed the README of the example to set up the environment variables with the Google Maps `API key` and `mapId` it somehow wasn't able to read the environment variables properly and had a fallback to a map with "For development purpose only" written on the tiles which is rasterised. I had to explicitly set the `API key` and `mapId` in the code to make it use my vector based map configuration.

### Environment

- Framework version: 9.2.2
- Browser: Chrome 141.0
- OS: macOS 26

### Logs

_No response_

### PR DESCRIPTION
**Pull request by felixpalmer**
Closes #9856 #9666.

Replaces https://github.com/visgl/deck.gl/pull/9877 & includes https://github.com/visgl/deck.gl/pull/9870

#### Background

Upgrading to luma@9.2 introduced `CanvasContext` as a new way of handling browser resizing. There are two area which were not implementing in deck to work with the new design in luma.gl:

- `onResize` [callback](https://github.com/visgl/luma.gl/blob/9.2-release/modules/core/src/adapter/canvas-context.ts#L379) was not registered
- `setDrawingBufferSize` never invoked (important in interleaved case where `autoResize = false`

I've verified with these changes that resizing is working in the following examples:

- `get-started/pure-js/google-maps`
- `get-started/react/google-maps`
- `get-started/pure-js/maplibre`
- `get-started/react/maplibre`

In each case I tested both interleaved `true` and `false`. All 8 variants are working with these fixes.

#### Change List
- Request a redraw using `_needsRedraw` when `CanvasContext.onResize()` is called
- Keep drawing buffer in sync with canvas when `autoResize = false`

---

> [!NOTE]
> Trigger redraw on CanvasContext resize and keep drawing buffer in sync (including when autoResize=false), while routing useDevicePixels via CanvasContext.
> 
> - **Core (deck.ts)**:
>   - **Resize handling**:
>     - Register `onResize` with luma device to set `_needsRedraw = 'Canvas resized'`, then call any user `onResize`.
>     - When `autoResize === false`, call `canvasContext.setDrawingBufferSize(width, height)` to sync drawing buffer with canvas.
>   - **Device pixel ratio**:
>     - Forward `useDevicePixels` via `canvasContext.setProps({useDevicePixels})` instead of manual resize hack.
>   - **Device creation**:
>     - Preserve and invoke user-provided `deviceProps.onResize` after internal handler.
>     - Pass `useDevicePixels` and `autoResize: true` to `createCanvasContext`.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 562bc7229e998ac5d467e26209a1018d123790b1. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

**Comment by chrisgervang** [comment]
This improves the typical resize window case for me!

There remains an issue where moving to a window with a different DPR doesn't trigger a resize / redraw.

Here's from high to low DPR:

https://github.com/user-attachments/assets/2dbf2d5e-4a81-4752-8d37-9db8f0c9e5cf
- maplibre, interleaved, purejs
- blank screen until hover interaction (triggers redraw)
- observe maplibre is too big. Fix by resizing window

Luma also provides a `onDevicePixelRatioChange`, but it wasn't as simple as adding it too since this didn't fix it:
Screenshot 2025-12-01 at 12 16 03 PM

https://github.com/visgl/deck.gl/pull/9877 had some combination of observation/redrawing/property updates that worked

**Comment by chrisgervang** [comment]
> important in interleaved case where autoResize = false

https://github.com/visgl/deck.gl/blob/88fdd61195945a3999f4831e90081d6ec51a45a4/modules/mapbox/src/mapbox-overlay.ts#L143

Mapbox interleaved modes has `autoResize = true`. I am not seeing the resize callbacks firing, nor the call to `setDrawingBufferSize` when running `get-started/pure-js/maplibre`

**Comment by chrisgervang** [comment]
I do see the callbacks firing when `interleaved: false`, and a noticeable improvement to rendering (it no longer clears the buffer on-resize).

**Comment by chrisgervang** [comment]
> > important in interleaved case where autoResize = false
> 
> https://github.com/visgl/deck.gl/blob/88fdd61195945a3999f4831e90081d6ec51a45a4/modules/mapbox/src/mapbox-overlay.ts#L143
> 
> Google and mapbox interleaved modes have `autoResize = true`. I've pushed to `chr/fix-dpr-9886` - can you try it out? I am not seeing the resize callbacks firing, nor the call to `setDrawingBufferSize` when running `get-started/pure-js/maplibre`

The resize callbacks don't fire with an interleaved overlay because they supply an external gl context, and that path uses `attach()` (which by default sets `autoResize = false`)

https://github.com/visgl/deck.gl/blob/2dc5d9a46b661a7ffac223ec0d63db1fcc046ec5/modules/core/src/lib/deck.ts#L369-L372

This means:
 - The resize callbacks would need to be added in the `createCanvasContext` deck prop within each overlay, if they're needed.
 - The google overlay didn't customize the `createCanvasContext` props, so `autoResize` _is_ `false`
 - The mapbox overlay does currently set `autoResize = true`

File: modules/core/src/lib/deck.ts [hunk 1]
```diff
@@ -485,23 +485,12 @@ export default class Deck<ViewsT extends ViewOrViews = null> {
...
-        borderBoxSize: [{inlineSize: canvas.clientWidth, blockSize: canvas.clientHeight}]
-      };
-      // Access the protected _handleResize method through the canvas context
-      (this.device.canvasContext as any)._handleResize([entry]);
+    if (props.useDevicePixels !== undefined && this.device?.canvasContext) {
+      this.device.canvasContext.setProps({useDevicePixels: props.useDevicePixels});
+    }
+    if (this.device?.canvasContext && this.device?.canvasContext.props.autoResize === false) {
+      const {width, height} = this.device.canvasContext.canvas;
+      this.device.canvasContext?.setDrawingBufferSize(width, height);
```
Comment (chrisgervang) [inline modules/core/src/lib/deck.ts:493]: Putting this in `setProps` means it only updates when props change. Why not add onResize callback to the attach device props instead so that it updates the drawing buffer when a resize event occurs? See #9887

**Comment by chrisgervang** [comment]
I ran through 15 test cases - resizing the window and moving them between monitors - and compiled my findings in https://github.com/visgl/deck.gl/pull/9887.

I recommend we merge those changes into this PR. The differences are:
- use event-driven resizing for external gl contexts instead of polling (add onResize to `attach()` instead of syncing in setProps)
- only set drawing buffer (which is what luma 9.3 will do, anyways)

**Review by chrisgervang — APPROVED** [review]

**Comment by akre54** [comment]
Thanks @felixpalmer !

**Comment by felixpalmer** [comment]
Thanks @chrisgervang @akre54 for the extensive testing. I'm merging this as is, in the interest of having small granular PRs
