### PR TITLE
fix(mapbox) Remove type dependency on mapbox-gl

### LINKED ISSUE #9211: [Bug] TypeScript error when using MapboxOverlay with "react-map-gl/maplibre"
### Description

I am getting the following error from TypeScript when using `useControl` from `react-map-gl/maplibre` and `MapboxOverlay` when following [the documentation](https://deck.gl/docs/developer-guide/base-maps/using-with-maplibre#example-interleaved-or-overlaid).

```
Type 'MapboxOverlay' does not satisfy the constraint 'IControl<MapInstance>'.
  Types of property 'onAdd' are incompatible.
    Type '(map: Map$1) => HTMLDivElement' is not assignable to type '(map: MapInstance) => HTMLElement'.
      Types of parameters 'map' and 'map' are incompatible.
        Type 'MapInstance' is missing the following properties from type 'Map$1': style, painter, _container, _missingCSSCanary, and 245 more.ts(2344)
```

(I spotted that somebody else has a similar issue in https://github.com/visgl/deck.gl/issues/8250#issuecomment-2264582777)

### Flavors

- [ ] Script tag
- [X] React
- [ ] Python/Jupyter notebook
- [X] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

No TypeScript error when using `useControl` with the `MapboxOverlay`. Or maybe we need something like `MaplibreOverlay`?

### Steps to Reproduce

Build the example that is [in the documenation](https://github.com/visgl/deck.gl/issues/8250#issuecomment-2264582777).

### Environment

- Framework version: 9.0.33
- Browser: N/A
- OS: macOS 14.6.1

### Logs

_No response_

### PR DESCRIPTION
**Pull request by Pessimistress**
Closes #9211

Dependency `@types/mapbox-gl` was removed in v9.0 (unintentionally?) by #8204
It wouldn't be compatible with maplibre-gl anyways...

#### Change List
- Remove type dependency on mapbox-gl

### CODE REVIEW

**Review by chrisgervang — APPROVED** [review]
Thanks! We could get surprised by a breaking change if we aren't directly importing from the libraries I suppose, but it's unlikely these interfaces will change much.

**Review by chrisgervang — COMMENTED** [review]
Should a package.json be changed, or are we still depending on mapbox-gl for something?

File: modules/mapbox/src/types.ts [hunk 1]
```diff
@@ -0,0 +1,123 @@
...
+  getPadding(): PaddingOptions;
+  getRenderWorldCopies(): boolean;
+
+  // mapbox v2+, maplibre v3+
+  getTerrain?(): any;
+  // mapbox v2+
+  getFreeCameraOptions?(): FreeCameraOptions;
+
+  // This is not a public property
+  transform?: any;
```
Comment (chrisgervang) [inline modules/mapbox/src/types.ts:118]: Would this benefit from typing the properties we do use?

Comment (Pessimistress) [reply modules/mapbox/src/types.ts:118]: The Transform classes in mapbox and maplibre are very different, I won't even bother...
