### PR TITLE
fix(widgets): use assigned viewport to change viewState

### LINKED ISSUE #8902: [Bug] Widgets without `viewId` don't change the view their automatically added to.
### Description

When a user is using `ZoomWidget` without supplying the optional `viewId` prop and they provide their own View, such as `views: new MapView({});`, the widget does not change the viewState because it does not target the custom view. The same is true for the `CompassWidget`.

### Flavors

- [ ] Script tag
- [x] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

Widgets with undefined `viewId` should still effect the view's they're placed in automatically.

### Steps to Reproduce

Add widgets to `examples/website/data-filter/app.tsx`:
```tsx
import {CompassWidget, ZoomWidget, FullscreenWidget} from '@deck.gl/widgets';
import '@deck.gl/widgets/stylesheet.css';

<DeckGL
  ...
  widgets={[new ZoomWidget({}), new CompassWidget({}), new FullscreenWidget({})]}
>
```

Click on the `+` button and nothing happens.

### Environment

- Framework version: deck.gl@9
- Browser: Chroms
- OS: MacOS

### Logs

_No response_

### PR DESCRIPTION
**Pull request by chrisgervang**
Closes #8902 

#### Change List
- use assigned viewport to change viewState

### CODE REVIEW

File: modules/widgets/src/compass-widget.tsx [hunk 1]
```diff
@@ -117,7 +117,7 @@ export class CompassWidget implements Widget<CompassWidgetProps> {
   }
 
   handleCompassReset() {
-    const viewId = this.viewId || 'default-view';
+    const viewId = this.viewId || this.viewport?.id || 'default-view';
```
Comment (felixpalmer) [inline modules/widgets/src/compass-widget.tsx:120]: Seems a bit clunky that this needs to be duplicated across widgets, it would be nice if we could push this complexity into the `WidgetManager` somehow. Also, can the `this.viewport?.id` ever be different from the `viewId`? If not, we could just do:

```ts
const viewId = this.viewport!.id || 'default-view';
```

**Review by felixpalmer — APPROVED** [review]

File: modules/widgets/src/compass-widget.tsx (hunk 1 above)
Comment (chrisgervang) [reply modules/widgets/src/compass-widget.tsx:120]: Widgets implement how they handle this themselves since not every viewport is tied to a view (FullscreenWidget has no view code in it).

I think viewId and viewport can differ in multi-view. I have some questions about multi-view widgets to look into next, so I'll follow up on this soon.

**Review by Pessimistress — APPROVED** [review]
