### PR TITLE
fix(core): Reset interaction state for smooth=false

### LINKED ISSUE #9845: [Bug] onInteractionStateChange no longer sets isZooming to false after zooming
### Description

`onInteractionStateChange` no longer sets `isZooming` to `false` after finishing a zoom-interaction. 
Works on versions 9.1.14 and earlier.

### Flavors

- [x] Script tag
- [x] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CARTO
- [ ] ArcGIS

### Expected Behavior

`onInteractionStateChange` sets `isZooming` to `false`

### Steps to Reproduce

Recreated by adding:
`onInteractionStateChange: (e) => console.log(e),`
to the `get-started/pure-js/basic` example.

### Environment

- Framework version: deck.gl >= 9.1.15
- Browser: Firefox
- OS: MacOS

### Logs

_No response_

### PR DESCRIPTION
**Pull request by felixpalmer**
Closes #9845, fixing regression introduced by #9769

#### Change List
- Manually reset state for `smooth=false` case
- Test

### CODE REVIEW

**Comment by DedaDev** [comment]
please merge this, also `isRotating` is missing

File: modules/core/src/controllers/controller.ts [hunk 1]
```diff
@@ -546,6 +546,12 @@ export default abstract class Controller<ControllerState extends IViewState<Cont
         isPanning: true
       }
     );
+
+    // When there's no transition (duration = 0), immediately reset interaction state
+    // since _onTransitionEnd callback won't fire
+    if (!smooth) {
+      this._setInteractionState({isZooming: false, isPanning: false});
```
Comment (chrisgervang) [inline modules/core/src/controllers/controller.ts:553]: Is there a reason not to reset all 5 states?
