### PR TITLE
fix(core): Enable shader/pipeline caching for attached WebGL devices

### LINKED ISSUE #9839: [Bug] Poor performance when enabling pickable on Firefox with DeckGL Version 9.2.2
### Description

After upgraded from version 9.1.8 to 9.2.2, I noticed a huge performance impact when using pickable layers on Firefox on both Windows 11 and MacOS 26.

There was no performance issues with the same code in 9.1.8 and there are no performance issues with using Edge/Chrome in 9.2.2.

Preview of what performance is like with Firefox:
https://github.com/user-attachments/assets/69e0d9f5-a879-4921-adde-b7f5608d8a77

### Flavors

- [ ] Script tag
- [x] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CARTO
- [ ] ArcGIS

### Expected Behavior

Pickable not to cause performance issues on Firefox

### Steps to Reproduce

1. Navigate to the GeoJson Highways sample using Firefox on Windows: https://deck.gl/examples/geojson-layer-paths
2. See instance performance impact
3. Checkout sample code and run with pickable disabled: https://github.com/visgl/deck.gl/tree/9.2-release/examples/website/highway
4. No more performance issues

### Environment

- Framework version: 9.2.2
- Browser: Firefox
- OS: Windows 11 / MacOS 26.0.1

### PR DESCRIPTION
**Pull request by michaelsaily**
When attaching to an external WebGL context (e.g., MapboxOverlay with interleaved: true), the caching props were not being set, unlike the _createDevice() path which explicitly enables them.

This caused severe performance degradation in interleaved mode because luma.gl's PipelineFactory would create new shader pipelines every frame instead of reusing cached ones.

The fix adds _cacheShaders: true and _cachePipelines: true to the webgl2Adapter.attach() call, matching the defaults set in _createDevice(). User-provided deviceProps can still override these if needed.

Closes #9839
Related: #9822, luma.gl#2465

---

> [!NOTE]
> **Low Risk**
> Small, localized default-prop change on the external-`gl` device attach path; main risk is unintended behavior change if an integration relied on caching being disabled.
> 
> **Overview**
> When `Deck` is created with an external `gl` context (via `webgl2Adapter.attach`), it now explicitly enables **shader** and **pipeline** caching by default (`_cacheShaders: true`, `_cachePipelines: true`), aligning attached-device behavior with the internal `_createDevice` path.
> 
> This is intended to prevent severe performance regressions in interleaved/external-context integrations (e.g. Mapbox overlays) where pipelines could otherwise be recreated every frame; user `deviceProps` can still override these flags via object spread order.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 2a6bb54e3ae105d67dfd34f6115316337299a5cc. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: modules/core/src/lib/deck.ts [hunk 1]
```diff
@@ -373,6 +373,10 @@ export default class Deck<ViewsT extends ViewOrViews = null> {
       const userOnResize = this.props.deviceProps?.onResize;
 
       deviceOrPromise = webgl2Adapter.attach(props.gl, {
+        // Enable shader and pipeline caching for attached devices (matches _createDevice defaults)
+        // Without this, interleaved mode (e.g., MapboxOverlay) creates new pipelines every frame
+        _cacheShaders: true,
+        _cachePipelines: true,
```
Comment (chrisgervang) [inline modules/core/src/lib/deck.ts:381]: Let's put this below the spread in case a user wants to customize their device props. By default `deviceProps` is a `{}` so the caching will still apply

**Review by chrisgervang — APPROVED** [review]
Thank you for submitting this PR - much appreciated! Left one comment. Please confirm there aren't any regressions to the other interleaved renderers - we now have a `examples/basemap-browser` app to help you quickly QA each integration

File: modules/core/src/lib/deck.ts (hunk 1 above)
Comment (michaelsaily) [reply modules/core/src/lib/deck.ts:381]: Awesome, thank you so much @chrisgervang! That's a great catch: I've gone ahead and made the required change. I've also gone ahead and manually verified the changes via the `examples/basemap-browser` that you had recommended, and can confirm that no regressions were found, having tested it across all integrations. 

Just as a slight note for anyone else wanting to verify the change: I believe that the performance impact scales with scene complexity and interaction frequency. As the `examples/basemap-browser` are quite simple, the problem doesn't always seem apparent, though this quickly changes in production applications with greater complexity and data.

Comment (chrisgervang) [reply modules/core/src/lib/deck.ts:381]: Oh my apologies, I misread your code. Your original code allowed the user to customize the props and now it forces the caching. Let's revert to your original version, please.

Comment (chrisgervang) [reply modules/core/src/lib/deck.ts:381]: Good to hear the example is working!

Comment (michaelsaily) [reply modules/core/src/lib/deck.ts:381]: Hahaha, no worries! Changes reverted and pushed.

**Comment by kylebarron** [comment]
This is great! Thank you! I can confirm this also fixes the bug I raised in https://github.com/visgl/deck.gl/issues/9941

Looking forward to having this published on NPM 🙂
