### PR TITLE
Only add necessary attributes in DataFilterExtension

### LINKED ISSUE #8694: [Bug] deckgl 9.0.1 did not render PathLayer and others
### Description

PathLayer and or GeoJSONLayer render LineString correctly. 

### Flavors

- [ ] Script tag
- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

PathLayer should render correctly,

### Steps to Reproduce

copy 
https://codepen.io/vis-gl/pen/mxxzdw

from the playground to

https://codepen.io/txtl-smith/pen/yLrPQpv

Add two extensions to ScatterPlotlayer, and the circle was not render. If there's on extension, the ScatterPlotLayer is rendered.

### Environment

- Framework version: deck.gl@9.0.1
- Browser: Chromium 118.0.5993.70
- OS: Windows

### Logs

 luma.gl: Model "TestPolygonLayer-child-fill-top: Ignoring constant supplied for unknown attribute "instanceElevations"
setConstantAttributes @ main.7fc60f3e.js:2
 luma.gl: Model "TestPolygonLayer-child-fill-top: Ignoring constant supplied for unknown attribute "instanceLineColors"
setConstantAttributes @ main.7fc60f3e.js:2
 luma.gl: Model "TestPolygonLayer-child-fill-top: Ignoring constant supplied for unknown attribute "instanceFilterCategoryValues"
setConstantAttributes @ main.7fc60f3e.js:2
 luma.gl: Model "TestPolygonLayer-child-stroke: Ignoring constant supplied for unknown attribute "filterCategoryValues"
setConstantAttributes @ main.7fc60f3e.js:2
 luma.gl: Model(TestPathLayer-child): Ignoring buffer "positions-buffer" for unknown attribute "positions"
setAttributes @ main.7fc60f3e.js:2
 luma.gl: Model(TestPathLayer-child): Ignoring buffer "instancePickingColors" for unknown attribute "instancePickingColors"
setAttributes @ main.7fc60f3e.js:2
 luma.gl: Model(TestPathLayer-child): Ignoring buffer "vertexPositions" for unknown attribute "vertexPositions"
setAttributes @ main.7fc60f3e.js:2
 luma.gl: Model(TestPathLayer-child): Ignoring buffer "vertexPositions" for unknown attribute "vertexPositions64Low"
setAttributes @ main.7fc60f3e.js:2
 luma.gl: Model(TestPathLayer-child): Ignoring buffer "vertexPositions" for unknown attribute "instanceLeftPositions"
setAttributes @ main.7fc60f3e.js:2
 luma.gl: Model(TestPathLayer-child): Ignoring buffer "vertexPositions" for unknown attribute "instanceLeftPositions64Low"
setAttributes @ main.7fc60f3e.js:2
 luma.gl: Model(TestPathLayer-child): Ignoring buffer "vertexPositions" for unknown attribute "instanceStartPositions"
setAttributes @ main.7fc60f3e.js:2
 luma.gl: Model(TestPathLayer-child): Ignoring buffer "vertexPositions" for unknown attribute "instanceStartPositions64Low"
setAttributes @ main.7fc60f3e.js:2
 luma.gl: Model(TestPathLayer-child): Ignoring buffer "vertexPositions" for unknown attribute "instanceEndPositions"
setAttributes @ main.7fc60f3e.js:2
 luma.gl: Model(TestPathLayer-child): Ignoring buffer "vertexPositions" for unknown attribute "instanceEndPositions64Low"
setAttributes @ main.7fc60f3e.js:2
 luma.gl: Model(TestPathLayer-child): Ignoring buffer "vertexPositions" for unknown attribute "instanceRightPositions"
setAttributes @ main.7fc60f3e.js:2
 luma.gl: Model(TestPathLayer-child): Ignoring buffer "vertexPositions" for unknown attribute "instanceRightPositions64Low"
setAttributes @ main.7fc60f3e.js:2
 luma.gl: Model(TestPathLayer-child): Ignoring buffer "instanceTypes" for unknown attribute "instanceTypes"
setAttributes @ main.7fc60f3e.js:2
 luma.gl: Model(TestPathLayer-child): Ignoring buffer "instanceStrokeWidths" for unknown attribute "instanceStrokeWidths"
setAttributes @ main.7fc60f3e.js:2
 luma.gl: Model(TestPathLayer-child): Ignoring buffer "instanceColors" for unknown attribute "instanceColors"
setAttributes @ main.7fc60f3e.js:2
 luma.gl: Model(TestPathLayer-child): Ignoring buffer "filterValues" for unknown attribute "filterValues"
setAttributes @ main.7fc60f3e.js:2
 luma.gl: Model(TestPathLayer-child): Ignoring buffer "filterValues" for unknown attribute "instanceFilterValues"
setAttributes @ main.7fc60f3e.js:2
 luma.gl: Model(TestPathLayer-child): Ignoring buffer "instanceDashArrays" for unknown attribute "instanceDashArrays"
setAttributes @ main.7fc60f3e.js:2
 luma.gl: Model "TestPathLayer-child: Ignoring constant supplied for unknown attribute "filterCategoryValues"
setConstantAttributes @ main.7fc60f3e.js:2
 luma.gl: Model "TestPathLayer-child: Ignoring constant supplied for unknown attribute "instanceFilterCategoryValues"
setConstantAttributes @ main.7fc60f3e.js:2
 luma.gl: Model "TestPathLayer-child: Ignoring constant supplied for unknown attribute "instanceDashOffsets"
setConstantAttributes @ main.7fc60f3e.js:2
 luma.gl: Model(TestGeoJSONLayer-child-linestrings): Ignoring buffer "positions-buffer" for unknown attribute "positions"
setAttributes @ main.7fc60f3e.js:2
 luma.gl: Model(TestGeoJSONLayer-child-linestrings): Ignoring buffer "instancePickingColors" for unknown attribute "instancePickingColors"
setAttributes @ main.7fc60f3e.js:2
 luma.gl: Model(TestGeoJSONLayer-child-linestrings): Ignoring buffer "vertexPositions" for unknown attribute "vertexPositions"
setAttributes @ main.7fc60f3e.js:2
 luma.gl: Model(TestGeoJSONLayer-child-linestrings): Ignoring buffer "vertexPositions" for unknown attribute "vertexPositions64Low"
setAttributes @ main.7fc60f3e.js:2
 luma.gl: Model(TestGeoJSONLayer-child-linestrings): Ignoring buffer "vertexPositions" for unknown attribute "instanceLeftPositions"
setAttributes @ main.7fc60f3e.js:2
 luma.gl: Model(TestGeoJSONLayer-child-linestrings): Ignoring buffer "vertexPositions" for unknown attribute "instanceLeftPositions64Low"
setAttributes @ main.7fc60f3e.js:2
 luma.gl: Model(TestGeoJSONLayer-child-linestrings): Ignoring buffer "vertexPositions" for unknown attribute "instanceStartPositions"
setAttributes @ main.7fc60f3e.js:2
 luma.gl: Model(TestGeoJSONLayer-child-linestrings): Ignoring buffer "vertexPositions" for unknown attribute "instanceStartPositions64Low"
setAttributes @ main.7fc60f3e.js:2
 luma.gl: Model(TestGeoJSONLayer-child-linestrings): Ignoring buffer "vertexPositions" for unknown attribute "instanceEndPositions"
setAttributes @ main.7fc60f3e.js:2
 luma.gl: Model(TestGeoJSONLayer-child-linestrings): Ignoring buffer "vertexPositions" for unknown attribute "instanceEndPositions64Low"
setAttributes @ main.7fc60f3e.js:2
 luma.gl: Model(TestGeoJSONLayer-child-linestrings): Ignoring buffer "vertexPositions" for unknown attribute "instanceRightPositions"
setAttributes @ main.7fc60f3e.js:2
 luma.gl: Model(TestGeoJSONLayer-child-linestrings): Ignoring buffer "vertexPositions" for unknown attribute "instanceRightPositions64Low"
setAttributes @ main.7fc60f3e.js:2
 luma.gl: Model(TestGeoJSONLayer-child-linestrings): Ignoring buffer "instanceTypes" for unknown attribute "instanceTypes"
setAttributes @ main.7fc60f3e.js:2
 luma.gl: Model(TestGeoJSONLayer-child-linestrings): Ignoring buffer "instanceStrokeWidths" for unknown attribute "instanceStrokeWidths"
setAttributes @ main.7fc60f3e.js:2
 luma.gl: Model(TestGeoJSONLayer-child-linestrings): Ignoring buffer "instanceColors" for unknown attribute "instanceColors"
setAttributes @ main.7fc60f3e.js:2
 luma.gl: Model(TestGeoJSONLayer-child-linestrings): Ignoring buffer "filterValues" for unknown attribute "filterValues"
setAttributes @ main.7fc60f3e.js:2
 luma.gl: Model(TestGeoJSONLayer-child-linestrings): Ignoring buffer "filterValues" for unknown attribute "instanceFilterValues"
setAttributes @ main.7fc60f3e.js:2
 luma.gl: Model(TestGeoJSONLayer-child-linestrings): Ignoring buffer "instanceDashArrays" for unknown attribute "instanceDashArrays"
setAttributes @ main.7fc60f3e.js:2
model.js:437 luma.gl: Model "TestGeoJSONLayer-child-linestrings: Ignoring constant supplied for unknown attribute "filterCategoryValues"
setConstantAttributes @ model.js:437
Show 1 more frame
Show less
model.js:437 luma.gl: Model "TestGeoJSONLayer-child-linestrings: Ignoring constant supplied for unknown attribute "instanceFilterCategoryValues"
setConstantAttributes @ model.js:437
Show 1 more frame
Show less
model.js:437 luma.gl: Model "TestGeoJSONLayer-child-linestrings: Ignoring constant supplied for unknown attribute "instanceDashOffsets"
setConstantAttributes @ model.js:437
Show 1 more frame
Show less
model.js:417 luma.gl: Model(TestGeoJSONLayer-child-points-circle): Ignoring buffer "positions-buffer" for unknown attribute "positions"
setAttributes @ model.js:417
Show 1 more frame
Show less
model.js:417 luma.gl: Model(TestGeoJSONLayer-child-points-circle): Ignoring buffer "instancePickingColors" for unknown attribute "instancePickingColors"
setAttributes @ model.js:417
Show 1 more frame
Show less
model.js:417 luma.gl: Model(TestGeoJSONLayer-child-points-circle): Ignoring buffer "instancePositions" for unknown attribute "instancePositions"
setAttributes @ model.js:417
Show 1 more frame
Show less
model.js:417 luma.gl: Model(TestGeoJSONLayer-child-points-circle): Ignoring buffer "instancePositions" for unknown attribute "instancePositions64Low"
setAttributes @ model.js:417
Show 1 more frame
Show less
model.js:417 luma.gl: Model(TestGeoJSONLayer-child-points-circle): Ignoring buffer "instanceRadius" for unknown attribute "instanceRadius"
setAttributes @ model.js:417
Show 1 more frame
Show less
model.js:417 luma.gl: Model(TestGeoJSONLayer-child-points-circle): Ignoring buffer "instanceFillColors" for unknown attribute "instanceFillColors"
setAttributes @ model.js:417
Show 1 more frame
Show less
model.js:417 luma.gl: Model(TestGeoJSONLayer-child-points-circle): Ignoring buffer "instanceLineColors" for unknown attribute "instanceLineColors"
setAttributes @ model.js:417
Show 1 more frame
Show less
model.js:417 luma.gl: Model(TestGeoJSONLayer-child-points-circle): Ignoring buffer "instanceLineWidths" for unknown attribute "instanceLineWidths"
setAttributes @ model.js:417
Show 1 more frame
Show less
model.js:417 luma.gl: Model(TestGeoJSONLayer-child-points-circle): Ignoring buffer "filterValues" for unknown attribute "filterValues"
setAttributes @ model.js:417
Show 1 more frame
Show less
model.js:417 luma.gl: Model(TestGeoJSONLayer-child-points-circle): Ignoring buffer "filterValues" for unknown attribute "instanceFilterValues"
setAttributes @ model.js:417
Show 1 more frame
Show less
model.js:417 luma.gl: Model(TestGeoJSONLayer-child-points-circle): Ignoring buffer "instanceStartAngle" for unknown attribute "instanceStartAngle"
setAttributes @ model.js:417
Show 1 more frame
Show less
model.js:417 luma.gl: Model(TestGeoJSONLayer-child-points-circle): Ignoring buffer "instanceEndAngle" for unknown attribute "instanceEndAngle"
setAttributes @ model.js:417
Show 1 more frame
Show less
model.js:437 luma.gl: Model "TestGeoJSONLayer-child-points-circle: Ignoring constant supplied for unknown attribute "filterCategoryValues"
setConstantAttributes @ model.js:437
Show 1 more frame
Show less
model.js:437 luma.gl: Model "TestGeoJSONLayer-child-points-circle: Ignoring constant supplied for unknown attribute "instanceFilterCategoryValues"
setConstantAttributes @ model.js:437
Show 1 more frame
Show less
model.js:437 luma.gl: Model "TestGeoJSONLayer-child-points-circle: Ignoring constant supplied for unknown attribute "instanceDashSegments"
setConstantAttributes @ model.js:437
Show 1 more frame
Show less
model.js:437 luma.gl: Model "TestGeoJSONLayer-child-points-circle: Ignoring constant supplied for unknown attribute "instanceDashColors"
setConstantAttributes @ model.js:437
Show 1 more frame
Show less
model.js:437 luma.gl: Model "TestGeoJSONLayer-child-points-icon: Ignoring constant supplied for unknown attribute "filterCategoryValues"
setConstantAttributes @ model.js:437
Show 1 more frame
Show less
model.js:437 luma.gl: Model "TestGeoJSONLayer-child-points-text-characters: Ignoring constant supplied for unknown attribute "filterCategoryValues"
setConstantAttributes @ model.js:437
Show 1 more frame
Show less
model.js:437 luma.gl: Model "TestIconLayer-child: Ignoring constant supplied for unknown attribute "filterCategoryValues"
setConstantAttributes @ model.js:437
Show 1 more frame
Show less
model.js:437 luma.gl: Model "TestLabelLayerNormal-child-characters: Ignoring constant supplied for unknown attribute "filterCategoryValues"
setConstantAttributes @ model.js:437
Show 1 more frame
Show less
model.js:459 luma.gl: Model.updateModuleSettings is deprecated. Use Model.shaderInputs.setProps()
updateModuleSettings @ model.js:459
Show 1 more frame
Show less
webgl-render-pipeline.js:243 Uncaught (in promise) Error: Error during linking: Too many attributes (instancePickingColors)
 
    at uu._reportLinkStatus (webgl-render-pipeline.js:243:23)
    at uu._linkShaders (webgl-render-pipeline.js:218:18)
    at new uu (webgl-render-pipeline.js:54:14)
    at Gu.createRenderPipeline (webgl-device.js:226:16)
    at Dd.createRenderPipeline (pipeline-factory.js:29:42)
    at Gd._updatePipeline (model.js:537:50)
    at new Gd (model.js:155:30)
    at wC._getModel (path-layer.js:249:16)
    at wC.updateState (path-layer.js:160:37)
    at wC._update (layer.js:777:22)
webgl-render-pipeline.js:243 Uncaught (in promise) Error: Error during linking: Vertex shader is not compiled.
 
    at uu._reportLinkStatus (webgl-render-pipeline.js:243:23)
    at uu._linkShaders (webgl-render-pipeline.js:218:18)
    at new uu (webgl-render-pipeline.js:54:14)
    at Gu.createRenderPipeline (webgl-device.js:226:16)
    at Dd.createRenderPipeline (pipeline-factory.js:29:42)
    at Gd._updatePipeline (model.js:537:50)
    at new Gd (model.js:155:30)
    at HS._getModel (scatterplot-layer.js:124:16)
    at HS.updateState (scatterplot-layer.js:97:37)
    at HS._update (layer.js:777:22)
model.js:417 luma.gl: Model(TestGeoJSONLayer-child-flash-linestrings): Ignoring buffer "positions-buffer" for unknown attribute "positions"
setAttributes @ model.js:417
Show 1 more frame
Show less
model.js:417 luma.gl: Model(TestGeoJSONLayer-child-flash-linestrings): Ignoring buffer "instancePickingColors" for unknown attribute "instancePickingColors"
setAttributes @ model.js:417
Show 1 more frame
Show less
model.js:417 luma.gl: Model(TestGeoJSONLayer-child-flash-linestrings): Ignoring buffer "vertexPositions" for unknown attribute "vertexPositions"
setAttributes @ model.js:417
Show 1 more frame
Show less
model.js:417 luma.gl: Model(TestGeoJSONLayer-child-flash-linestrings): Ignoring buffer "vertexPositions" for unknown attribute "vertexPositions64Low"
setAttributes @ model.js:417
Show 1 more frame
Show less
model.js:417 luma.gl: Model(TestGeoJSONLayer-child-flash-linestrings): Ignoring buffer "vertexPositions" for unknown attribute "instanceLeftPositions"
setAttributes @ model.js:417
Show 1 more frame
Show less
model.js:417 luma.gl: Model(TestGeoJSONLayer-child-flash-linestrings): Ignoring buffer "vertexPositions" for unknown attribute "instanceLeftPositions64Low"
setAttributes @ model.js:417
Show 1 more frame
Show less
model.js:417 luma.gl: Model(TestGeoJSONLayer-child-flash-linestrings): Ignoring buffer "vertexPositions" for unknown attribute "instanceStartPositions"
setAttributes @ model.js:417
Show 1 more frame
Show less
model.js:417 luma.gl: Model(TestGeoJSONLayer-child-flash-linestrings): Ignoring buffer "vertexPositions" for unknown attribute "instanceStartPositions64Low"
setAttributes @ model.js:417
Show 1 more frame
Show less
model.js:417 luma.gl: Model(TestGeoJSONLayer-child-flash-linestrings): Ignoring buffer "vertexPositions" for unknown attribute "instanceEndPositions"
setAttributes @ model.js:417
Show 1 more frame
Show less
model.js:417 luma.gl: Model(TestGeoJSONLayer-child-flash-linestrings): Ignoring buffer "vertexPositions" for unknown attribute "instanceEndPositions64Low"
setAttributes @ model.js:417
Show 1 more frame
Show less
model.js:417 luma.gl: Model(TestGeoJSONLayer-child-flash-linestrings): Ignoring buffer "vertexPositions" for unknown attribute "instanceRightPositions"
setAttributes @ model.js:417
Show 1 more frame
Show less
model.js:417 luma.gl: Model(TestGeoJSONLayer-child-flash-linestrings): Ignoring buffer "vertexPositions" for unknown attribute "instanceRightPositions64Low"
setAttributes @ model.js:417
Show 1 more frame
Show less
model.js:417 luma.gl: Model(TestGeoJSONLayer-child-flash-linestrings): Ignoring buffer "instanceTypes" for unknown attribute "instanceTypes"
setAttributes @ model.js:417
Show 1 more frame
Show less
model.js:417 luma.gl: Model(TestGeoJSONLayer-child-flash-linestrings): Ignoring buffer "instanceStrokeWidths" for unknown attribute "instanceStrokeWidths"
setAttributes @ model.js:417
Show 1 more frame
Show less
model.js:417 luma.gl: Model(TestGeoJSONLayer-child-flash-linestrings): Ignoring buffer "Buffer-37" for unknown attribute "instanceColors"
setAttributes @ model.js:417
Show 1 more frame
Show less
model.js:417 luma.gl: Model(TestGeoJSONLayer-child-flash-linestrings): Ignoring buffer "filterValues" for unknown attribute "filterValues"
setAttributes @ model.js:417
Show 1 more frame
Show less
model.js:417 luma.gl: Model(TestGeoJSONLayer-child-flash-linestrings): Ignoring buffer "filterValues" for unknown attribute "instanceFilterValues"
setAttributes @ model.js:417
Show 1 more frame
Show less
model.js:417 luma.gl: Model(TestGeoJSONLayer-child-flash-linestrings): Ignoring buffer "instanceDashArrays" for unknown attribute "instanceDashArrays"
setAttributes @ model.js:417
Show 1 more frame
Show less
model.js:437 luma.gl: Model "TestGeoJSONLayer-child-flash-linestrings: Ignoring constant supplied for unknown attribute "filterCategoryValues"
setConstantAttributes @ model.js:437
Show 1 more frame
Show less
model.js:437 luma.gl: Model "TestGeoJSONLayer-child-flash-linestrings: Ignoring constant supplied for unknown attribute "instanceFilterCategoryValues"
setConstantAttributes @ model.js:437
Show 1 more frame
Show less
model.js:437 luma.gl: Model "TestGeoJSONLayer-child-flash-linestrings: Ignoring constant supplied for unknown attribute "instanceDashOffsets"
setConstantAttributes @ model.js:437
Show 1 more frame
Show less
model.js:417 luma.gl: Model(TestGeoJSONLayer-child-flash-linestrings): Ignoring buffer "Buffer-36" for unknown attribute "instanceColors"
setAttributes @ model.js:417
Show 1 more frame
Show less
webgl-render-pipeline.js:243 Uncaught (in promise) Error: Error during linking: Too many attributes (instancePickingColors)
 
    at uu._reportLinkStatus (webgl-render-pipeline.js:243:23)
    at uu._linkShaders (webgl-render-pipeline.js:218:18)
    at new uu (webgl-render-pipeline.js:54:14)
    at Gu.createRenderPipeline (webgl-device.js:226:16)
    at Dd.createRenderPipeline (pipeline-factory.js:29:42)
    at Gd._updatePipeline (model.js:537:50)
    at Gd.setBufferLayout (model.js:316:30)
    at wC._setModelAttributes (layer.js:586:19)
    at wC.updateAttributes (layer.js:498:18)
    at wC._updateAttributes (layer.js:522:14)

### PR DESCRIPTION
**Pull request by felixpalmer**
Closes #8694

#### Change List
- Allow `0` as value for `filterSize` & `categorySize`
- Only add attribute to shader for non-zero sizes
- Default `categorySize` to `0` to fix breaking change in v9
- Test & doc update

### CODE REVIEW

File: modules/extensions/src/data-filter/shader-module.ts [hunk 1]
```diff
@@ -6,33 +6,43 @@ import {glsl} from '../utils/syntax-tags';
...
+  #else
+    #define DATAFILTER_ATTRIB instanceFilterValues
+    #define DATAFILTER_ATTRIB_64LOW instanceFilterValues64Low
+  #endif
+
+  in DATAFILTER_TYPE DATAFILTER_ATTRIB;
+  #ifdef DATAFILTER_DOUBLE
+    in DATAFILTER_TYPE DATAFILTER_ATTRIB_64LOW;
+
+    uniform DATAFILTER_TYPE filter_min64High;
```
Comment (ibgreen) [inline modules/extensions/src/data-filter/shader-module.ts:32]: Thought: I would have focused on just `#ifdef`-ing out the attributes, and not have worried about the uniforms. Based on the principle that less conditional code is better, so we should use it sparingly.

Also we should be moving towards uniform buffers and there is not much penalty for having unused fields in a uniform buffer (or even "global" uniforms).

File: modules/extensions/src/data-filter/shader-module.ts [hunk 2]
```diff
@@ -6,33 +6,43 @@ import {glsl} from '../utils/syntax-tags';
...
 
-in DATAFILTER_TYPE DATAFILTER_ATTRIB;
-#ifdef DATAFILTER_DOUBLE
-  in DATAFILTER_TYPE DATAFILTER_ATTRIB_64LOW;
 
-  uniform DATAFILTER_TYPE filter_min64High;
-  uniform DATAFILTER_TYPE filter_max64High;
+#ifdef DATACATEGORY_TYPE
+  #ifdef NON_INSTANCED_MODEL
+    #define DATACATEGORY_ATTRIB filterCategoryValues
```
Comment (ibgreen) [inline modules/extensions/src/data-filter/shader-module.ts:40]: Looking at this, I ask myself if we really want to require an attribute that can be applied in both instanced and non-instanced usage should be renamed. This simple renaming adds a lot of clutter to this shader.

File: modules/extensions/src/data-filter/shader-module.ts [hunk 3]
```diff
@@ -48,45 +58,48 @@ float dataFilter_reduceValue(vec3 value) {
 float dataFilter_reduceValue(vec4 value) {
   return min(min(value.x, value.y), min(value.z, value.w));
 }
-void dataFilter_setValue(DATAFILTER_TYPE valueFromMin, DATAFILTER_TYPE valueFromMax, DATACATEGORY_TYPE category) {
-  if (filter_enabled) {
+
+#ifdef DATAFILTER_ATTRIB
```
Comment (ibgreen) [inline modules/extensions/src/data-filter/shader-module.ts:62]: The code is kind of hard to review as one has to guess what these `#defines` mean. Perhaps declaring a `defines` type above the shader with comments could be a way.

```
type defines = {
  /* ... */
  DATAFILTER_ATTRIB?: boolean,
 ...
};
```

File: modules/extensions/src/data-filter/shader-module.ts [hunk 4]
```diff
@@ -48,45 +58,48 @@ float dataFilter_reduceValue(vec3 value) {
...
       );
     } else {
       dataFilter_value = dataFilter_reduceValue(
         step(filter_min, valueFromMin) * step(valueFromMax, filter_max)
       );
     }
+  }
+#endif
 
+#ifdef DATACATEGORY_ATTRIB
```
Comment (ibgreen) [inline modules/extensions/src/data-filter/shader-module.ts:77]: While there is some possible performance gains from removing the entire function, I wonder if we could just have commented out the parts of it that are dependent on conditional attributes in order to reduce the combinatorial explosion of various code paths - each of this has the potential to be invisible to the compiler in our normal test cases and therefore could be prone to "code rot".

**Review by ibgreen — APPROVED** [review]
Just thoughts around the theme that less conditional code could be a goal worth considering.

**Comment by Pessimistress** [comment]
Can you add a few render tests (data filter, category filter & both)?

File: modules/extensions/src/data-filter/shader-module.ts (hunk 4 above)
Comment (felixpalmer) [reply modules/extensions/src/data-filter/shader-module.ts:77]: I considered that, but then it is messy because there are many combinations of function parameters that may or may not be needed depending on the enabled filter

File: modules/extensions/src/data-filter/shader-module.ts (hunk 1 above)
Comment (felixpalmer) [reply modules/extensions/src/data-filter/shader-module.ts:32]: These need to be inside the `#ifdef` as their type is `DATAFILTER_TYPE`

**Review by Pessimistress — APPROVED** [review]
