### PR TITLE
fix(core): redraw() should clear canvas by default

### LINKED ISSUE #8529: [Bug] Updating the `layers` prop each frame in non-interleaved `MapboxOverlay` leads to increased opacity and flickering
### Description

When zooming or moving the deck.gl layers are rendered more than once, leading to increased opacity or flickering.

### Flavors

- [ ] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [X] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

Should not flicker or change opacity.

### Steps to Reproduce

Controlled by `enableBug3` in https://github.com/JayFoxRox/deck.gl-bugs/blob/master/src/DeckGlBugs.tsx

### Environment

- Framework version: deck.gl@9.0.0-beta.4
- Browser: All
- OS: Probably all, but at least macOS (Not sure if relevant, but this is on a 120Hz display)

### Logs

_No response_

### PR DESCRIPTION
**Pull request by donmccurdy**
- Fixes #8529

### CODE REVIEW

**Comment by Pessimistress** [comment]
How does the animation loop clear the canvas before this?

**Comment by donmccurdy** [comment]
I set a breakpoint at ...

https://github.com/visgl/luma.gl/blob/1bd3342c78793f6cf548f2c798c41e44a048490f/modules/webgl/src/adapter/resources/webgl-render-pass.ts#L130-L132

... and hopped around a few demos. I could only find examples that ...

1. clear depth and stencil buffer, not color
2. clear color of the picking FBO

On `master`, it looks like we're not clearing color at all, but are relying on [`preserveDrawingBuffer=false`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/getContext#preservedrawingbuffer) to get the canvas cleared. If I enable `preserveDrawingBuffer=true`, the canvas isn't cleared:

https://github.com/visgl/deck.gl/assets/1848368/4df561b8-e439-45ae-aecb-f5cd78b939df


So somehow we need to make sure this option gets passed into the RenderPass constructor. Whether this is the best place to put that option, I'm not sure!

**Comment by Pessimistress** [comment]
In v8 `clearCanvas` is used in `LayersPass` and has a default value of `true`:

https://github.com/visgl/deck.gl/blob/44b8edf30833f227bd0a160b3422bb038b3e9c27/modules/core/src/passes/layers-pass.ts#L73-L80

On master `clearCanvas` is also used in `LayersPass` but no longer has a fallback:

https://github.com/visgl/deck.gl/blob/e075fa7a471d44b89232e360a92cfcc2ffb0ffba/modules/core/src/passes/layers-pass.ts#L59-L71

We have some pretty obscure integration use cases where `redraw()`, `_drawLayers()` are called directly. Just for the sake of not disturbing things too much, I suggest we move this into `LayerPass` like v8.

**Comment by Pessimistress** [comment]
FYI I can also confirm that without mapbox, the most basic usage: 

```js
new Deck({
  deviceProps: {
    preserveDrawingBuffer: true
  },
  ...
});
```

The canvas does not clear between frames.

**Comment by donmccurdy** [comment]
Current dependencies on/for this PR:
* **#8543** <a href="https://app.graphite.dev/github/pr/visgl/deck.gl/8543?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/visgl/deck.gl/8543?utm_source=stack-comment).

**Comment by donmccurdy** [comment]
@Pessimistress agreed! I've moved it into LayersPass in 161dff7d7464556c8805919b4a6a5b9d5d0361f9. It's in `render()` rather than `_drawLayers()` because that's where the render pass is created, but `LayersPass#_drawLayers` is private and used nowhere else, so this should be equivalent.

File: modules/core/src/passes/layers-pass.ts [hunk 1]
```diff
@@ -59,14 +59,15 @@ export default class LayersPass extends Pass {
...
 
     const renderPass = this.device.beginRenderPass({
       framebuffer: options.target,
       parameters: {
         viewport: [0, 0, width, height]
       },
       // clear depth and color buffers, restoring transparency
-      clearColor: options.clearColor ?? (options.clearCanvas ? [0, 0, 0, 0] : false),
+      clearColor: options.clearColor ?? (clearCanvas ? [0, 0, 0, 0] : false),
       clearDepth: options.clearCanvas ? 1 : undefined
```
Comment (Pessimistress) [inline modules/core/src/passes/layers-pass.ts:71]: Use fallback value?

Comment (donmccurdy) [reply modules/core/src/passes/layers-pass.ts:71]: Oh! Depth is already being cleared, and I think the reason clarifies how this broke in the first place:

https://github.com/visgl/luma.gl/blob/3ff710ed1685088f6148ea1b2e6b4fb2cb585d5c/modules/webgl/src/adapter/resources/webgl-render-pass.ts#L125-L136

We're checking `props.clearFoo !== false` in WebGLRenderPass, so an undefined is equivalent to clearing by default. But we do `(clearCanvas ? [0, 0, 0, 0] : false)` above, turning an `undefined` into `false`.

So maybe I should just remove the default from LayersPass too, and make sure it passes through undefined if `clearColor` and `clearCanvas` were not specified?

Comment (donmccurdy) [reply modules/core/src/passes/layers-pass.ts:71]: ... alternatively, we could remove the `clearCanvas` prop, it isn't widely used in the codebase, and use `clearColor` directly instead.

Comment (Pessimistress) [reply modules/core/src/passes/layers-pass.ts:71]: I suspect this breaks mapbox/google maps interleaving, as they specify `clearCanvas: false` and expect depth not be cleared. The mapbox example is currently broken pending @chrisgervang 's PR. Any reason `undefined` is used here? @Ibgreen

Comment (donmccurdy) [reply modules/core/src/passes/layers-pass.ts]: Makes sense. I've pushed another change that I think handles this as expected, if a bit verbosely. But also happy to wait on clarification and/or mapbox example updates.

Comment (ibgreen) [reply modules/core/src/passes/layers-pass.ts]: It seems to me that we should define how we want luma.gl RenderPass props to work. 
- I believe this API went through a few iterations as WebGPU is quite different from WebGL here 
- (clear can only be done as part of beginning a new RenderPass),
- and they have "load" constants for preserving contents of previous scene (which is apparently more expensive than clearing)
- If we revise the API, We could argue that one has to specify `clearXYZ: ...` to actually get things cleared, i.e. `undefined` should be no clearing. Even though that default is (slightly) more expensive.

Comment (Pessimistress) [reply modules/core/src/passes/layers-pass.ts]: I don't think we need to change anything in luma, but your clarification on performance impact is be very helpful. I think the right thing to do is explicitly setting the `clear*` behaviors here instead of falling through to luma's RenderPass defaults.

Comment (donmccurdy) [reply modules/core/src/passes/layers-pass.ts]: If luma.gl's RenderPass didn't clear by default, we'd still use WebGL's `preserveDrawingBuffer=false` by default, correct? That's certainly fine with me, and perhaps what I'd expect given luma.gl's lower level of abstraction.

And then deck.gl's LayersPass would probably do the opposite — clear unless otherwise specified.

Comment (donmccurdy) [reply modules/core/src/passes/layers-pass.ts]: Just updated the PR to specify clearColor and clearDepth explicitly in LayersPass.

**Review by Pessimistress — APPROVED** [review]
